#include <bits/stdc++.h>
using namespace std;const int MOD=998244353;
long long pw(long long a,long long e){long long r=1;for(;e;e>>=1,a=a*a%MOD)if(e&1)r=r*a%MOD;return r;}
long long fast(int n,const vector<int>&p,const vector<pair<int,int>>&E){if(n==1)return 1;vector<vector<int>>g(n);vector<int>who(n+1);for(int i=0;i<n;i++)who[p[i]]=i;for(auto [u,v]:E){g[u].push_back(v);g[v].push_back(u);}vector<int>up(n,1);for(int val=n;val>=1;--val){int v=who[val];for(int w:g[v])if(p[w]>p[v])up[v]+=up[w];}vector<int>par(n,-1),ord{0};for(size_t z=0;z<ord.size();++z){int v=ord[z];for(int w:g[v])if(w!=par[v]){par[w]=v;ord.push_back(w);}}auto factor=[&](int ch,int pa){return p[pa]<p[ch]?up[ch]:up[ch]-up[pa];};long long d=1;for(int v:ord)if(v)d=d*factor(v,par[v])%MOD;vector<int>D(n);D[0]=d;for(size_t z=1;z<ord.size();++z){int v=ord[z],u=par[v];D[v]=(long long)D[u]*pw(factor(v,u),MOD-2)%MOD*factor(u,v)%MOD;}long long fact=1;for(int i=1;i<=n-1;i++)fact=fact*i%MOD, fact%=MOD;long long ans=0;for(int r=0;r<n;r++){bool ok=1;for(int w:g[r])if(p[w]>p[r])ok=0;if(ok)ans=(ans+fact*pw(D[r],MOD-2))%MOD;}return ans;}
long long brute(int n,const vector<int>&p,const vector<pair<int,int>>&E){int m=n-1;if(m==0)return 1;vector<int>ord(m);iota(ord.begin(),ord.end(),0);long long ans=0;do{vector<char>used(n);bool ok=1;for(int id:ord){auto [u,v]=E[id];if(used[u]&&used[v]){ok=0;break;}if(!used[u]&&!used[v])used[p[u]<p[v]?u:v]=1;else used[used[u]?v:u]=1;}ans+=ok;}while(next_permutation(ord.begin(),ord.end()));return ans%MOD;}
vector<pair<int,int>> tree_from_prufer(int n,uint64_t code){if(n==1)return {};if(n==2)return {{0,1}};vector<int>seq(n-2);for(int i=0;i<n-2;i++){seq[i]=code%n;code/=n;}vector<int>deg(n,1);for(int x:seq)deg[x]++;set<int>leaf;for(int i=0;i<n;i++)if(deg[i]==1)leaf.insert(i);vector<pair<int,int>>e;for(int x:seq){int v=*leaf.begin();leaf.erase(leaf.begin());e.push_back({v,x});if(--deg[x]==1)leaf.insert(x);}int a=*leaf.begin();leaf.erase(leaf.begin());int b=*leaf.begin();e.push_back({a,b});return e;}
int main(){uint64_t cnt=0;for(int n=1;n<=5;n++){uint64_t trees=(n<=2?1:1);if(n>2)for(int i=0;i<n-2;i++)trees*=n;for(uint64_t code=0;code<trees;code++){auto E=tree_from_prufer(n,code);vector<int>p(n);iota(p.begin(),p.end(),1);do{auto f=fast(n,p,E),b=brute(n,p,E);++cnt;if(f!=b){cerr<<"FAIL exhaustive n="<<n<<" tree="<<code<<" f="<<f<<" b="<<b<<"\n";return 1;}}while(next_permutation(p.begin(),p.end()));}}
mt19937 rng(31415926);for(int tc=0;tc<1000000;tc++){int n=1+rng()%7;vector<pair<int,int>>E;for(int v=1;v<n;v++)E.push_back({v,(int)(rng()%v)});vector<int>p(n);iota(p.begin(),p.end(),1);shuffle(p.begin(),p.end(),rng);auto f=fast(n,p,E),b=brute(n,p,E);++cnt;if(f!=b){cerr<<"FAIL random tc="<<tc<<" n="<<n<<" f="<<f<<" b="<<b<<"\n";for(int x:p)cerr<<x<<' ';cerr<<'\n';for(auto e:E)cerr<<e.first<<'-'<<e.second<<' ';cerr<<'\n';return 1;}}
cout<<"PASS "<<cnt<<" instances\n";
}